Merge upstream

diff --git a/.github/workflows/custom.yml b/.github/workflows/custom.yml
--- a/.github/workflows/custom.yml
+++ b/.github/workflows/custom.yml
@@ -105,7 +105,7 @@ jobs:
 
           echo "BUILD_ARGS=$build_args" >> $GITHUB_ENV
           python build.py $build_args
-        continue-on-error: true
+        continue-on-error: false
       - id: check_issue
         name: Check issue feature file
         run: |
@@ -121,20 +121,30 @@ jobs:
         with:
           name: issue-fea-file
           path: fonts/issue.fea
-      - name: Create release
-        run: |
-          if [ ! -d "fonts/archive" ]; then
-            echo "Error: Failed to build font, please check [Run custom script] step."
-            exit 1
-          fi
-          echo "### Build arguments" >> NOTES
-          echo "\`\`\`" >> NOTES
-          echo "python build.py $BUILD_ARGS" >> NOTES
-          echo "\`\`\`" >> NOTES
-          echo "### Final Configuration" >> NOTES
-          echo "\`\`\`" >> NOTES
-          python build.py $BUILD_ARGS --dry | sed '1s/^/font_config: /' >> NOTES
-          echo "\`\`\`" >> NOTES
-          gh release create "v$(date +%s)" fonts/archive/*.* --notes-file NOTES
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Create release
+      #   run: |
+      #     if [ ! -d "fonts/archive" ]; then
+      #       echo "Error: Failed to build font, please check [Run custom script] step."
+      #       exit 1
+      #     fi
+      #     echo "### Build arguments" >> NOTES
+      #     echo "\`\`\`" >> NOTES
+      #     echo "python build.py $BUILD_ARGS" >> NOTES
+      #     echo "\`\`\`" >> NOTES
+      #     echo "### Final Configuration" >> NOTES
+      #     echo "\`\`\`" >> NOTES
+      #     python build.py $BUILD_ARGS --dry | sed '1s/^/font_config: /' >> NOTES
+      #     echo "\`\`\`" >> NOTES
+      #     gh release create "v$(date +%s)" fonts/archive/*.* --notes-file NOTES
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Upload build artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: custom-build
+          path: fonts/archive/*.*
+          if-no-files-found: error
+          retention-days: 0 
+          compression-level: 9
+          overwrite: true
+          include-hidden-files: true
